- hosts: devops
  become: yes

  tasks:
    - name: Ensure jenkins user exists
      become: yes
      user:
        name: jenkins
        shell: /bin/bash
        create_home: yes

    - name: Create project directory
      file:
        path: /opt/devops-project
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Install required packages
      become: yes
      apt:
        name:
          - openjdk-17-jdk
          - curl
          - gnupg
          - docker.io
          - git
          - unzip
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins GPG key
      become: yes
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key \
        | gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg
      args:
        creates: /usr/share/keyrings/jenkins-keyring.gpg


    - name: Add Jenkins repository
      become: yes
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian binary/

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install Jenkins
      become: yes
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install kops
      get_url:
        url: https://github.com/kubernetes/kops/releases/download/v1.28.0/kops-linux-amd64
        dest: /usr/local/bin/kops
        mode: '0755'

